--
-- AUTOMATION: Stream + Task
-- Automatically triggers RUN_RAG_PIPELINE when new PDFs
-- land in the stage.
--
-- uploads PDF -> stream detects it -> task fires ->
-- RUN_RAG_PIPELINE() runs -> agent updated automatically
--
-- To pause:  ALTER TASK RAG.PUBLIC.RAG_PIPELINE_TASK SUSPEND;
-- To resume: ALTER TASK RAG.PUBLIC.RAG_PIPELINE_TASK RESUME;
-- To check history:
--   SELECT * FROM TABLE(RAG.INFORMATION_SCHEMA.TASK_HISTORY(
--       TASK_NAME => 'RAG_PIPELINE_TASK'
--   )) ORDER BY SCHEDULED_TIME DESC LIMIT 10;
-- 

CREATE OR REPLACE STREAM RAG.PUBLIC.RAG_STAGE_STREAM
    ON STAGE RAG.PUBLIC.RAG_INTERNAL
    COMMENT = 'Detects new PDF files uploaded to RAG_INTERNAL stage';

CREATE OR REPLACE TASK RAG.PUBLIC.RAG_PIPELINE_TASK
    WAREHOUSE = ML_WH
    SCHEDULE  = '5 MINUTE'
    COMMENT   = 'Auto-triggers RAG pipeline when new PDFs land in stage'
    WHEN SYSTEM$STREAM_HAS_DATA('RAG.PUBLIC.RAG_STAGE_STREAM')
AS
    CALL RAG.PUBLIC.RUN_RAG_PIPELINE();

ALTER TASK RAG.PUBLIC.RAG_PIPELINE_TASK RESUME;

SHOW STREAMS LIKE 'RAG_STAGE_STREAM'  IN SCHEMA RAG.PUBLIC;
SHOW TASKS   LIKE 'RAG_PIPELINE_TASK' IN SCHEMA RAG.PUBLIC;
