
-- TABLE: DEMO_SEC_IMAGE_CORPUS
-- One row per page PNG - input for AI_EMBED

CREATE TABLE IF NOT EXISTS RAG.PUBLIC.DEMO_SEC_IMAGE_CORPUS (
    FILE_NAME    VARCHAR       NOT NULL,
    DOC_PAGE_KEY VARCHAR       NOT NULL,
    PAGE_NUMBER  INTEGER       NOT NULL,
    SOURCE_DOC   VARCHAR,
    STAGE_PREFIX VARCHAR       NOT NULL DEFAULT '@RAG.PUBLIC.RAG_INTERNAL',
    CREATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_IMAGE_CORPUS PRIMARY KEY (FILE_NAME)
);
