
-- TABLE: INGESTION_LOG
-- Tracks every PDF processed by the pipeline
-- Status: PENDING -> PAGINATED -> EMBEDDED -> INDEXED -> ERROR


CREATE TABLE IF NOT EXISTS RAG.PUBLIC.INGESTION_LOG (
    FILE_NAME   VARCHAR       NOT NULL,
    FILE_SIZE   NUMBER        NOT NULL DEFAULT 0,
    FILE_MD5    VARCHAR,
    SOURCE_TYPE VARCHAR       NOT NULL,
    STATUS      VARCHAR       NOT NULL DEFAULT 'PENDING',
    ERROR_MSG   VARCHAR,
    CREATED_AT  TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT  TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_INGESTION_LOG PRIMARY KEY (FILE_NAME)
);
