
-- TABLE: DEMO_SEC_PARSE_DOC
-- LAYOUT-mode text + table extraction per page PDF


CREATE TABLE IF NOT EXISTS RAG.PUBLIC.DEMO_SEC_PARSE_DOC (
    FILE_NAME        VARCHAR       NOT NULL,
    DOC_PAGE_KEY     VARCHAR       NOT NULL,
    PAGE_NUMBER      INTEGER       NOT NULL,
    STAGE_PREFIX     VARCHAR       NOT NULL,
    PARSE_DOC_OUTPUT VARIANT,
    CREATED_AT       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PARSE_DOC PRIMARY KEY (FILE_NAME)
);
