
-- TABLE: DEMO_SEC_PDF_CORPUS
-- One row per page PDF - input for PARSE_DOCUMENT


CREATE TABLE IF NOT EXISTS RAG.PUBLIC.DEMO_SEC_PDF_CORPUS (
    FILE_NAME    VARCHAR       NOT NULL,
    DOC_PAGE_KEY VARCHAR       NOT NULL,
    PAGE_NUMBER  INTEGER       NOT NULL,
    STAGE_PREFIX VARCHAR       NOT NULL,
    CREATED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PDF_CORPUS PRIMARY KEY (FILE_NAME)
);
