
-- TABLE: DEMO_SEC_VM3_VECTORS
-- voyage-multimodal-3 embeddings per page image


CREATE TABLE IF NOT EXISTS RAG.PUBLIC.DEMO_SEC_VM3_VECTORS (
    FILE_NAME    VARCHAR             NOT NULL,
    DOC_PAGE_KEY VARCHAR             NOT NULL,
    PAGE_NUMBER  INTEGER             NOT NULL,
    STAGE_PREFIX VARCHAR             NOT NULL,
    IMAGE_VECTOR VECTOR(FLOAT, 1024),
    CREATED_AT   TIMESTAMP_NTZ       NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_VM3_VECTORS PRIMARY KEY (FILE_NAME)
);
